
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.ide_sql.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELOP = 2;
  public static final int INSERTAR = 13;
  public static final int DIGIT = 18;
  public static final int VALUE = 20;
  public static final int ELIMINAR = 17;
  public static final int IDENTIFIER = 19;
  public static final int ERROR = 21;
  public static final int RCURLYBRKT = 7;
  public static final int FILTRAR = 10;
  public static final int VALORES = 14;
  public static final int LOGICALOP = 3;
  public static final int ASIGNAR = 16;
  public static final int ACTUALIZAR = 15;
  public static final int COMMA = 8;
  public static final int EOINSTR = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int ALLCOLUMNS = 5;
  public static final int EN = 12;
  public static final int SELECCIONAR = 11;
  public static final int LCURLYBRKT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RELOP",
  "LOGICALOP",
  "EOINSTR",
  "ALLCOLUMNS",
  "LCURLYBRKT",
  "RCURLYBRKT",
  "COMMA",
  "DOT",
  "FILTRAR",
  "SELECCIONAR",
  "EN",
  "INSERTAR",
  "VALORES",
  "ACTUALIZAR",
  "ASIGNAR",
  "ELIMINAR",
  "DIGIT",
  "IDENTIFIER",
  "VALUE",
  "ERROR"
  };
}

